# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34c85f7c0641377a0d378df0af7b0a36e7e880cbc105dcbc062952695a320b2bb5eb403cbef0c9f1386667a146ed253a65fa5e4eae44c292db3e9fe7a847aa8d

test:
  secret_key_base: 6af43facde07bcd1a5d3da908ae191adf56d4e98f5a840ef6c6797d703a35b0897fb29365b53f10814cd835caa75cd6db2412a8988cde6558cd21f8d91b9680b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
